apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bp8hmyydo-nodejs
  janus-idp.io/tekton: bp8hmyydo-nodejs
  backstage.io/kubernetes-id: bp8hmyydo-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bp8hmyydo-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
