apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bp8hmyydo-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bp8hmyydo-nodejs 
  name: bp8hmyydo-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: bp8hmyydo-nodejs 
